### ISSUE TITLE
More unused resources... 

### ISSUE THREAD

**Issue by rohands** [systers/PCSA-Android#154]
As a follow up to #128, there are more unused resources in the app.
There are 17 unused imports which can be removed. I'd like to remove them.

**Comment by sandarumk** [comment]
What are the unwanted resources and where do you find them?

**Comment by rohands** [comment]
@sandarumk The code inspect tool in Android shows all the unused resources and issues with the current code. Apart from the 17 unused imports, there are many more redundant declarations like those. I'd like to take this issue and solve all the related bugs

**Comment by chamika** [comment]
I agree with @rohands and by running lint inspection I found following issues in the application. 
Here are the issues gathered in the latest source. (03/28/2016)
[PCSA-Issues](http://chamika.github.io/PCSA-Issues/)

**Comment by rohands** [comment]
@chamika thank you for helping. 
Just to clarify, 
Whatever you have posted is the just the output of Android Lint right?

**Comment by chamika** [comment]
@rohands  Yes. As I mentioned in my above comment, these are the issues I found running the lint inspection.

**Comment by chamika** [comment]
@rohands Yes, after running lint inspection, you can export it as HTML. Exported files are added so that everyone can access the report. This is handy when you need to describe the issues rather than going for a high-level overview. As I see it also helps to avoid duplication of the issue so that anybody can get a good idea on the unused resources.

**Comment by chamika** [comment]
@sandarumk This is just a suggestion. We can open up a separate issue in the issue tracker with this lint output and tag it as a beginner task so that any newcomers can come and get one from the list and fix it. It will help a lot of new people to start up on this project.

I hope @rohands will also agree to this.

**Comment by rohands** [comment]
@chamika First of all, I feel you should have filtered out some of the issues which came as output from the code inspection since not all the issues can be fixed. Like you already know, design changes are generally not acceptable unless otherwise specified by PeaceCorps themselves. 
And yes, I feel it's a good idea to tag <strong>some</strong> of these issues as beginner tasks. I think @sandarumk could give us more guidance on this. 
Also, I'm not sure who implemented the frames part in your markup. But it's a bad practice. I hope you wouldn't mind improvising on it if you were the one who implemented it.  @chamika Thank you for your suggestions, again.

**Comment by chamika** [comment]
@rohands 
Clarification regarding the markup: As I said earlier, this is the HTML report generated by using Android Studio. I just uploaded the report and didn't modify. 

Suggestion on unacceptable issues:  We can run the lint for selected inspections and get the report so that beginners will not work on unnecessary changes. Or else the project members can choose what should and shouldn’t be fixed and mention them in the issue so that it would be clear to beginners.

**Comment by rohands** [comment]
@chamika I feel the latter is a better option. That would also mean a change in the current README file regarding steps to contribute. 
Also, I feel other issues which involve documentation changes like the one in #94 could be tagged as beginner issues. By doing so, beginners can run through the entire code and understand how the features are implemented. 
I see that you have opened the issue #94. So maybe after you implement the basic version, I hope you wouldn't mind beginners taking the other tasks up.

**Comment by chamika** [comment]
@rohands  True. Thank you for bringing that up.  I have already included the method template. What are left is the class comments and licensing information which I have inquired now. When that is settled would love to implement your idea on opening that as a beginner issue after the basic implementation is done.

**Comment by sandarumk** [comment]
Actually what @chamika suggested is a good idea. Good work on exporting the lint output. I will go though the link and select what are relevant and make a separate issue for beginners. No changes in READ ME is necessary. I only have to tag the issue "free" and clarify how to claim separate items in the description.
@rohands if you want to fix the issue related to the 17 unused imports you are free to do so. When you are done, we can ask @chamika to update his link with the latest. If not we can add that too in the beginner task list.

**Comment by rohands** [comment]
@sandarumk you can add this issue too.

**Comment by rohands** [comment]
@sandarumk This issue can be closed. 
The outcome of this issue was the newly proposed beginner issue list. Thanks to @chamika for exporting the lint output.

**Comment by sandarumk** [comment]
I will close the issue after I created the new one.

**Comment by sandarumk** [comment]
#222 Created.
