### ISSUE TITLE
Message Dialog Box

### ISSUE THREAD

**Issue by Mayankmkh** [systers/PCSA-Android#156]
Issue 1 : It would be beneficial to use a function instead of MessageDialogBox class.
Issue 2 : Instead of ArrayAdapter we can use a string array to display the contents in the dialog
Issue 3 : Radio buttons displaying in dialog are of no use.

I would like to solve these issues.

**Comment by rohands** [comment]
@Mayankmkh 

Regarding your issue 1 : 
MessageDialogBox class is in a seperate class to make use of the advantages of the DialogFragment API which Android provides us. The benefits of having it are many. Actually, in order to handle configuration changes, it is advisable to create a Dialog Fragment rather than registering other handlers or any other workarounds you can find over the net
Another thing is that, the same code isn't being reused anywhere else, so I don't think making it a function would matter a lot. 

Regarding your issue 3: 
This is more of a design issue. PeaceCorps has already given the design template. According to my previous experience with contributions to this Project, changes to design is generally not accepted.

**Comment by Mayankmkh** [comment]
Thank you for the information and your support.
What about the issue 2?

**Comment by rohands** [comment]
@Mayankmkh I'm just another contributor like you. I commented here because you had an issue with a feature that I had contributed earlier and I had to convince you and the team why I chose to make a separate class and why that's the best way of doing it. 
Maybe @sandarumk or @Buddhiprabha will get you going further. 
Thank you.

**Comment by Mayankmkh** [comment]
@rohands As I'm new to open source so it will take some time to understand the community.
By the way, one more issue that I found is that the MessageDialogBox class uses parameterized construction, instead we should be using Bundles. I would like to solve this issue too

**Comment by rohands** [comment]
Yes, but there is a problem. If you did observe properly, I'm trying to get the context of the calling activity into this class.
Would you know how to store non-primitive types like that into a bundle? I tried Serializable but I couldn't cast it back.

**Comment by rohands** [comment]
@Mayankmkh 
As a supplement to whatever I have mentioned, 
<a href="http://stackoverflow.com/questions/23683281/save-object-reference-to-bundle-in-android">Link to storing object reference in bundle</a> should probably convince you why we should not store reference to objects in Bundles.

**Comment by Mayankmkh** [comment]
@rohands As in the link [Why not to use non-default constructor](http://stackoverflow.com/questions/11602433/fragment-newinstance-vc-onsaveinstancestate/11602478#11602478) , the reason to  not to use no-default constructor is that whenever the fragment is recreated, the default constructor is called. So, can we instead make a function to pass the reference?

**Comment by rohands** [comment]
Do you mean you want to write a getter function from the calling fragment?
In that case, why would you want to do it is my question? Or maybe a better
question would be how is it better than the current implementation?
Your concern might be that on configuration change, it will call only the
default constructor? So this is where using the DialogFragment API comes
into picture. Android saves the state of the dialogbox and manages its
creation based on the activity's lifecycle. Isn't it wonderful design by
itself? Why would you want to do extra work on your side?

**Comment by Mayankmkh** [comment]
@rohands Thank you for clearing the image. It's great what android can do for us.

As all issues are resolved so the Issue should be now closed
