### ISSUE TITLE
Auto detect location using network connectivity

### ISSUE THREAD

**Issue by fatimarafiqui** [systers/PCSA-Android#171]
The mobile application can automatically detect the location after the launch with the help of network connectivity, with or without gps. In case the the location is not Uganda, Syria or Tunisia the location, the user will be asked for their location.

**Comment by sandarumk** [comment]
The location is Uganda, Syria or Tunisia because that is where the staff are available. So there is no use in adding a different location. As I can remember the location is saved as shared preferences so you only have to set it once. There is actually  no need of location detection in this scenario. It will only add additional overhead.

**Comment by fatimarafiqui** [comment]
The issue is if a person in Syria and installs the app, the default location is Uganda. What I am suggesting is by default the location will be detected automatically at once. We can eliminate the other
locations.

**Comment by fatimarafiqui** [comment]
The Information in Get help now section mentions it is for Uganda, i.e it is location specific.
The issue is If a person is in Syria, the default location will be set as Uganda after the installation. What I was suggesting is the location can automatically be set at once after the first app launch. In case, the location does not get detected the user can select it manually as well.

**Comment by sandarumk** [comment]
That is why we had shared preferences save the location. So if you save it once it won't change unless you change it. So that we do not have to eliminate other locations as well. Additional overhead like auto detection of network will only be needed in the activities like Circle of Trust where you need the network to call and send SMS. Otherwise for this scenario it not crucial.

**Comment by fatimarafiqui** [comment]
I understand that it is not so much crucial. But we are improving the user experience, even if it is for once.TelephonyManager is the class which can be used to detect the network you were saying about and the same can be used to detect the country of the service provider. This will add no overhead as such. Please let me know on this, so that i can contribute to the repository in a better way.

**Comment by sandarumk** [comment]
We will put this into the suggestion list which will be discussed with Peace corps.
