### ISSUE TITLE
Trustees Photo not showing up in the Circle of trust

### ISSUE THREAD

**Issue by PrabhanshuAttri** [systers/PCSA-Android#172]
In the circle of trust section, the trustees' photographs are not showing up, nor their names which makes it difficult to recognise the trustees and identify the number of vacant positions of trustees.

**Comment by sandarumk** [comment]
The current functionality do not have the name. So that is actually not an issue. If you have gone through the closed issues you may have noticed that it was repeatedly suggested and rejected. However we are going to implement adding the name with further discussions with the Peace corps. If the trustee is added from contacts the contact picture should be visible. Otherwise there will be a default picture. If there is a bug in that scenario please mention that in the comments with the screen shots so we can identify where it went wrong.

**Comment by sandarumk** [comment]
Any update on this or can I close this issue?

**Comment by PrabhanshuAttri** [comment]
I figured out that the contact photographs are working fine when saved as a profile photo for the existing contact in the contact directory. In that case, the issue must be closed. You may consider adding trustees' names. :)

**Comment by sandarumk** [comment]
Adding trustees name was earlier rejected by Peace corps, but later added as a requirement which should be covered in this year GSoC. You can find the discussions on this (rejection) in the closed issues. The new suggestion is given with the UI update provided by peace corps (Which is one of the issues with scope for GSoC)
