### ISSUE TITLE
Focus remains on the same EditText after retrieving contact

### ISSUE THREAD

**Issue by rohands** [systers/PCSA-Android#218]
After we pick a contact to register a particular comrade, normally focus should move to the next element (next EditText), but in this case it remains in the same EditText. Needs to be fixed

**Comment by yogeshbalan** [comment]
@rohands Please don't get me wrong on this, but I think an issue much be broader in scope. The issues #217 and #218 can be merged into one single issue names **Modification in UI elements of comrade assigning activity**. 
Otherwise it will only increase the no. of issues whatsoever. I guess you are getting my point.

**Comment by rohands** [comment]
@yogeshbalan I agree with you, I shall tag them into one if approved. Thanks for your suggestion :)

**Comment by sandarumk** [comment]
@rohands You can fix this.

**Comment by sandarumk** [comment]
solved by #244 and merged.
