### ISSUE TITLE
Location detection starts happening only on opening Circle of Trust 

### ISSUE THREAD

**Issue by rohands** [systers/PCSA-Android#230]
As we already know, the user of the app is most likely to use the feature "Circle of Trust" only during cases of emergency.
In the current implementation, the SMSs that are sent out are included with/without location based on the availability of the user's location. The code which detects the location runs only when the user enters Circle of Trust. The point to note is that during emergencies, considering the delay in retrieving the location, there is a very slight possibility of retrieving location and sending it along with the message.
. 
I suggest that we should run the code to retrieve the location updates when the user enters the app itself and not wait till he clicks "Circle of Trust". 

Another suggestion is about caching the last known location. Some people may question me about this feature since the Android API provides a way of getting the last known location through the Location Manager class. But this is true and makes sense if the location updates are being received not only when the user clicks on Circle of Trust. Or we could just cache the result, maybe using SharedPreferences. 

I'd like to fix this issue

**Comment by sandarumk** [comment]
Thank you for the suggestion. If the user do not want the circle of trust functionality of the app, running the location service when the app starts will add an additional overhead since it is a high cost activity regarding battery life. 
Caching the last location and sending it have the risk of sending the wrong location. Sending the wrong location is worse than using no location. 
It is not that the location is needed as soon as the circle of trust /help me is clicked. When the circle of trust starts, user has to click the help me button and then choose the message type before sending it. So there is already some time intervel to detect the location.
