### ISSUE TITLE
Refactor drawables in midmap 

### ISSUE THREAD

**Issue by chamika** [systers/PCSA-Android#241]
As the issue #225 suggests, midmap drawables should be used for launcher icons only.
Latest source contains other drawables in midmap directories. They should be moved to drawables-xxx directories.

**Comment by sandarumk** [comment]
Can you list out the incorrect drawables which are still in the mimap directory?

**Comment by yogeshbalan** [comment]
After merging PR #232 the `ic_message_option.png` goes back into **/mipmap** folder.
I think it would be better if these rules are updated in wiki or ReadMe to insure that in future developers place drawables in their respective appropriate folders. 
Sorry, if I am wrong

**Comment by sandarumk** [comment]
@chamika you can fix the issue.
@yogeshbalan sure. I will take care of that.

**Comment by chamika** [comment]
Here are the files
`/res/mipmap-hdpi/ic_message_option.png`
`/res/mipmap-mdpi/ic_message_option.png`
`/res/mipmap-xhdpi/ic_message_option.png`
`/res/mipmap-xxhdpi/ic_message_option.png`
`/res/mipmap-xxxhdpi/ic_message_option.png`

**Comment by rohands** [comment]
Hi developers.
Needed to clarify why exactly they're being placed in drawable?
I would like to also mention that (since I'm responsible for why it went to
mipmap) I didn't intentionally put them there. I created an image asset in
android studio and that automatically placed the files there. Are we saying
this is a wrong thing to do? Isn't creating an image asset the right thing
to do?

**Comment by yogeshbalan** [comment]
Hi Rohands,
Well by default AS always generate icons out if *Image Asset*. That is why they are bring placed in **/mipmap**.
It is on developer to change the location to **/drawable** if he/she is using image asset to generate drawable that would not be used as launcher icon.

**Comment by rohands** [comment]
@yogeshbalan
Would you please guide me to the docs which says so?
Also, I might have been mislead by
http://stackoverflow.com/questions/29047902/how-to-add-an-image-to-the-drawable-folder-in-android-studio#comment46335057_29047902
On 15-Apr-2016 4:39 pm, "Yogesh Kumar" <notifications@github.com> wrote:

Hi Rohands,
Well by default AS always generate icons out if *Image Asset*. That is why
they are bring placed in */mipmap*.
It is on developer to change the location to */drawable* if he/she is using
image asset to generate drawable that would not be used as launcher icon.

—
You are receiving this because you commented.

Reply to this email directly or view it on GitHub
<https://github.com/systers/PCSA-Android/issues/241#issuecomment-210418996>

**Comment by sandarumk** [comment]
@rohands  Please follow the conversation at the original issue. I think that has all the information you need.

**Comment by rohands** [comment]
@sandarumk
Thank you

**Comment by sandarumk** [comment]
Merged.
