### ISSUE TITLE
Home Page UI Enhancement.

### ISSUE THREAD

**Issue by pandilladivya** [systers/PCSA-Android#287]
__UI Improvement__ : 

In the main page icons can be added to the buttons to make the UI more user friendly

**Current Home Page**

![image](https://cloud.githubusercontent.com/assets/16818129/19901644/cb0ba982-a08d-11e6-83c1-5b44edacd2bb.png)

**Here is a screenshot of what can be done**

![image](https://cloud.githubusercontent.com/assets/16818129/19901480/3fa6e3f2-a08d-11e6-85a6-d1b537a91696.png)

**Comment by saketkumar95** [comment]
Are you working on this or should i work?

**Comment by rohands** [comment]
@saketkumar95 @pandilladivya 
Changes to the UI of the app are not recommended since the UI is pre-decided by a team which sends out prototypes and expects the app to look the same way. If there are any logical issues, please do open them and work on them. But as far as possible, please do refrain from opening issues related to User Interface because nothing can be changed without the approval of the Peace Corps.

**Comment by rohands** [comment]
Although you could do one thing. I noticed that some part of the content is overlapping with the status bar. Shift the contents to come below the transclusent status bar. Make sure that this is supported both for Android Lollipop (and above versions) and Kitkat version since they behave differently in each of these cases.

**Comment by sandarumk** [comment]
@saketkumar95 Please read the README first and understand the issue assigning process of this project. @pandilladivya you can fix what @rohands suggested and send a PR.

**Comment by pandilladivya** [comment]
@rohands Thank you for the suggestion :)
@sandarumk Sure ma'm Thank you!

**Comment by sandarumk** [comment]
@pandilladivya your suggested UI improvement is nice. I have already added this to discussion with peacecorps. Will let you know if they approved the new improvement.

**Comment by pandilladivya** [comment]
@sandarumk Thank You :)
