### ISSUE TITLE
Double backpress to exit.

### ISSUE THREAD

**Issue by m-murad** [systers/PCSA-Android#315]
In most of the apps if the user presses back button to exit, a toast message appears which prompts the user to press back button again to exit.

I suggest implementing the same in this app

**Comment by calistus** [comment]
This feature is only suitable for games, or app which has sessions like banking apps, computer based tests, etc. The reason why UX designers put this feature in an app is because they do not want the user 
kill a session unknowingly and may be getting to the home screen the app requires a lot of verification.

As for PCSA getting to the home screen is just a tap away so no need for that prompt. If a user mistakenly  exit, getting back to is just a tap away.
So no need for this feature
