### ISSUE TITLE
Missing '.' and spacing between points in some activities.

### ISSUE THREAD

**Issue by ashu-dadhich** [systers/PCSA-Android#344]
According to mock-up their should be spacing between each point and each should be ended with full stop. Certain activities are not following it.
**eg:-**
![image](https://cloud.githubusercontent.com/assets/15179401/21490173/9f18c1ec-cc17-11e6-8b32-f201c846a01f.png)

**Comment by sandarumk** [comment]
There are few issues with this bullet point view in various screens. Can you go through all the screens and check whether there are more related issues rather than the inconsistency of the full stop and the space in the beginning. Also check whether how much of these problems will be solved with adding the justification library.

**Comment by ashu-dadhich** [comment]
Yeah sure I would gladly do it.

**Comment by ashu-dadhich** [comment]
@sandarumk just to make sure I understood what you meant correctly you are referring to issues like this right:
**eg:** 
![image](https://cloud.githubusercontent.com/assets/15179401/21538912/ba74f8aa-cdc7-11e6-98ec-d9ae230e5297.png)
**Here the points in char. of sexual assault should be like tactics of sexual assualt  **

![image](https://cloud.githubusercontent.com/assets/15179401/21539022/a5026bb4-cdc8-11e6-85c1-e043a16b2bd7.png)

**Comment by ashu-dadhich** [comment]
@sandarumk I have put all the issues I found related to bullet points in the attached pdf please review them and for this gone through each screen with the mock up being my reference.
[issues-bullet.pdf](https://github.com/systers/FirstAide-Android/files/676942/issues-bullet.pdf)
Hope I did it correctly. 
_Thank you_

**Comment by ashu-dadhich** [comment]
Using BulletSpan might be a good idea to correct them.
https://developer.android.com/reference/android/text/style/BulletSpan.html

**Comment by sandarumk** [comment]
Here are my comments on the issues
(1) Already reported. tagged as GCI.
(3)Use complete words. Your descriptions lack in clarity. When you say it should be indented add an example screenshot, how it should be indented.
(4) Your description is unclear
(5) Forget about the mockup. but the middle alignment is not good. Should be left aligned.(Will be fixed to justify when you are done with the justification issue right?)
(6) It is okay the way it is.
(7) No difference between the two screens. But since the issue which is already commented here. It is a valid issue. Please update the document with the screenshots.
Please do the changes and upload a new one.

**Comment by ashu-dadhich** [comment]
[issues-bullet.pdf](https://github.com/systers/FirstAide-Android/files/679612/issues-bullet.pdf)
Please review the new document
One more thing I wanted to ask is in the #337 is the comparison table sufficient I uploaded in the new document or do I need to add more points of comparison among the three libraries.
_Thank you_

**Comment by sandarumk** [comment]
I will have a look at it. Please don't mix issues. Keep the issues separated. If you have anything to clarify, use that issue.

**Comment by sandarumk** [comment]
Remove the header with @sandarumk comment. If you want to add the changes you can do it by versioning and keeping a version history table. It is cleaner that way. If not you can just communicate these information via the comments. When you are preparing a documentation for something, make sure that it is understandable to anyone who reads it (Which means anyone who do not follow this discussion as well.). So if you are going to answer to a question via the document, include both the question and the answer or include answer in such a way that it can be understandable. "Yes fixing the justification would correct its alignment"  This comment is not needed in the document. Since the document in only about issues and not how to fix them. Use a consistent fonts and headings. Be consistent with the font colors too. If you are going to use red for the issue, do that in every issue. It would be better if your image sizes follow the same consistency.

**Comment by ashu-dadhich** [comment]
Sorry about that won't happen again.
Should I correct the document as well?

**Comment by sandarumk** [comment]
yes you should.

**Comment by ashu-dadhich** [comment]
[issues-bullet(final).pdf](https://github.com/systers/FirstAide-Android/files/688002/issues-bullet.final.pdf)
Corrected the suggested changes in the document.

**Comment by ashu-dadhich** [comment]
@sandarumk I wanted to ask that I should solve this issue after the justification PR is merged right?

**Comment by sandarumk** [comment]
You can start working on this. If you need a clarification on the content, there is a closed issue called general content update. You can find that issue and check with the document which is attahed to that issue.

**Comment by ashu-dadhich** [comment]
I will check it and get back to you soon one thing I wanted I wanted to ask is **version history table** that you mentioned earlier in the comments can you tell me more about.
_Thank you_

**Comment by sandarumk** [comment]
http://www.technicalcommunicationcenter.com/2014/06/23/how-to-design-a-document-revision-history-template/

**Comment by ashu-dadhich** [comment]
Just to make sure I got it correctly I have to do the following:

- make changes keeping in mind the given link https://drive.google.com/file/d/0B8cm8EBZg0GaQy1CUkRUOXhWZUE/view

- attach a document containing the DOCUMENT REVISION HISTORY TABLE in this issue page regularly keep updating it with the changes being made.

- make separate PR's for the issues and keep a track of them in the document.

**Please correct me if I misunderstood something**

**Comment by sandarumk** [comment]
Forget the document and do the PR. The revision history was a suggestion to improve your documentation.

**Comment by ashu-dadhich** [comment]
on it!

**Comment by ashu-dadhich** [comment]
@sandarumk I am finished with my PR.
But would like to make sure if other things in the app are in line with the document as well. Can I? or should  I just send the PR.
_Thank you_

**Comment by sandarumk** [comment]
fixed via #368
