### ISSUE TITLE
Into(Circle Of Trust) Contains Pixelated Pictures

### ISSUE THREAD

**Issue by madhavrathi** [systers/PCSA-Android#388]
![screenshot_2017-03-02-17-35-57-245_com peacecorps pcsa](https://cloud.githubusercontent.com/assets/22375731/23506956/cebc3e9c-ff70-11e6-8bab-fe57cb819d2e.png)
![screenshot_2017-03-02-17-36-03-272_com peacecorps pcsa](https://cloud.githubusercontent.com/assets/22375731/23506957/cee1f36c-ff70-11e6-958b-cc517a74c650.png)
![screenshot_2017-03-02-17-36-12-635_com peacecorps pcsa](https://cloud.githubusercontent.com/assets/22375731/23506958/cf0817e0-ff70-11e6-981e-9f05afae2840.png)

@sandarumk  Can i send PR for this ? Thanks

**Comment by sandarumk** [comment]
@madhavrathi We have identified this issue. In last Google Code In we added a task to design the icons in circle of trust. We can do the same here as well. For the 'Help Me' button we can use one of the suggested images which will be used in circle of trust as well. So let's keep it aside for a while. For the third screen, you can add a new image with more  quality and send a PR. If you have any suggestions for the first screen image, can you add them here. If it matches our requirement we can go forward with that too. For now, can you first send a PR with the fix for the last screen?

**Comment by madhavrathi** [comment]
@sandarumk  Please review https://github.com/systers/FirstAide-Android/pull/399 
and this PR also solves Issue #336.

**Comment by madhavrathi** [comment]
And my suggestions for Image in First Screen :- 
![circle_of_trust2](https://cloud.githubusercontent.com/assets/22375731/23580636/83c5770c-012b-11e7-849b-cecbca25dd3d.png)
![circle_of_trust3](https://cloud.githubusercontent.com/assets/22375731/23580638/83c86408-012b-11e7-9fe4-278eb5e76176.jpg)
![circle-of-trust1](https://cloud.githubusercontent.com/assets/22375731/23580637/83c80ec2-012b-11e7-8578-9629d8f59654.jpg)

**Comment by sandarumk** [comment]
What about the copy rights or licencing of these images?

**Comment by madhavrathi** [comment]
Please Review this PR https://github.com/systers/FirstAide-Android/pull/400.
I apologize for taking on an issue assigned to someone else.
About the copyright issue I am not aware of the  licensing . Can i design a few mocks myself ?

**Comment by madhavrathi** [comment]
@sandarumk 
Please Review this https://github.com/systers/FirstAide-Android/pull/401
I apologize for taking on an issue assigned to someone else.
About the copyright issue I am not aware of the licensing . Can i design a few mocks myself ?

**Comment by rohands** [comment]
@madhavrathi Design issues are not entertained by the team since they have been proposed earlier and approved by the PeaceCorps themselves. However, we'll take this suggestion while communicating with them next. Thank you :)
