### ISSUE TITLE
Transparent Application Icon

### ISSUE THREAD

**Issue by swapsha96** [systers/PCSA-Android#389]
You can see it's difficult to see the logo and and read the title on it. It becomes a big problem is user created its shortcut in home screen and has white background.

![screenshot_20170303-101605](https://cloud.githubusercontent.com/assets/14021461/23538760/b2921a94-fffb-11e6-815d-c8c91e73c30c.png)

I can fix it by creating Material Design like circular or square icon (with shadow) by adding green(or any other color) as background color. Should I drop examples below?

**Comment by swapsha96** [comment]
@sandarumk  How about this?

![web_hi_res_512](https://cloud.githubusercontent.com/assets/14021461/23541318/a170c57e-000c-11e7-9552-86f8fd46a789.png)

**Comment by sandarumk** [comment]
This issue is valid. But we have to make a decision with the iOS team as well. I can remember this is reported as an issue or mentioned in the slack channel for discussion. Let's put this onhold until the discussions with iOS team finishes and agreed on a common ground and also discuss with Peace Corps about the icon change since this is suggested by them.
Do not send a PR unless your issue is approved by a maintainer to avoid unnecessary work. Please read through the READ ME and the wiki.
