### ISSUE TITLE
Implementing Confidentiality as in Mockup.pdf

### ISSUE THREAD

**Issue by scopeInfinity** [systers/PCSA-Android#56]
Mockup.pdf : https://github.com/systers/PCSA-Android/raw/develop/docs/design/mockup.pdf

**Comment by sandarumk** [comment]
Hi, Thank you for your interest in the PCSA project. Please note that we are in a middle of design upgrade process. Will update the mockup.pdf as soon as possible. Meanwhile the content for Confidentiality section is not yet fully decided. If you want to contribute, rather than suggesting new development, please find bugs and improvements in the current functionality.
