### ISSUE TITLE
Comrade description

### ISSUE THREAD

**Issue by AaskaShah** [systers/PCSA-Android#59]
Just a suggestion :)
It would be helpful if comrade name is also stored with the number , and on clicking on any comrade a pop up window shows the description of comrade

**Comment by sandarumk** [comment]
In the comrade screen the only thing clickable should be the middle "Help Me" button and the edit button according to the approved UI. (The mockup is outdated and we are currently updating it). We will keep your suggestion in mind for the name (Since it has already been suggested by many people. see the closed issues). There is currently an improvement going on to add the contact picture of the comrades instead of the default picture too. We are currently not seeking to change the current UI. (That does not mean the UI won't change in the future.) Thank you very much for your effort. We appreciate your interest in our project and looking forward to future contributions.

**Comment by AaskaShah** [comment]
Thank you :)

**Comment by sandarumk** [comment]
Please refer #36
